# ed_semantics.yaml
# EventSemantics for ED visit data.

identity:        ed_visit
entity_id_col:   patient_id
date_col:        ed_visit_date
also_defined_by:
  - hospital_id
descriptor_cols:
  icd10_condition:
    type:     category
    timeline: unique
  systolic_bp:
    type:     numeric
    timeline: average
