"""
without_eventus_stacked_timeline.py

Attempts to reproduce the stacked timeline from Chapter 5 of the
eventus vignette series using standard matplotlib — no eventus.

Plots a stacked timeline of Medicaid coverage for a random sample
of 50 members, where each member has a different observation window
(ages 18-25).

Generated by a large language model given identical specifications.

Run from repo root:
    python vignettes/without_eventus/without_eventus_stacked_timeline.py
"""
import pathlib
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D

# ── Global constants ──────────────────────────────────────────────────────────

ENTITY_COL  = "patient_id"
START_COL   = "coverage_start"
END_COL     = "coverage_end"
DOB_COL     = "date_of_birth"

DATE_FLOOR   = pd.Timestamp("1920-01-01")
DATE_CEILING = pd.Timestamp("2030-01-01")
DATA_START   = pd.Timestamp("2018-01-01")
DATA_END     = pd.Timestamp("2025-12-31")
AGE_START    = 18
AGE_END      = 25

# Visual constants — hardcoded, not versioned
COLOR_ACTIVE    = "#9FC0F6"
COLOR_BEFORE    = "#FAFAF9"
COLOR_AFTER     = "#FAFAF9"
COLOR_GAP       = "#F6C3A4"
COLOR_NO_EPISODES = "#FAF9F9"
BOUNDARY_COLOR  = "#6B7C93"
ALPHA_ACTIVE    = 0.85
ROW_HEIGHT      = 0.5
BAR_HEIGHT      = 0.95
FIG_WIDTH       = 16
FIG_HEIGHT      = 8
FONT_SIZE       = 14
TITLE_FONT_SIZE = 20
STYLE           = "seaborn-v0_8-whitegrid"
N_SAMPLE        = 50
RANDOM_SEED     = 42

OUTPUT_DIR = pathlib.Path(__file__).parent.parent / "chapter_05_stacked_timeline" / "output"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ── Load data ─────────────────────────────────────────────────────────────────

DATA_DIR = pathlib.Path(__file__).parent.parent / "data"
demog_df = pd.read_csv(DATA_DIR / "simulated_member_demographics.csv")
raw_df   = pd.read_csv(DATA_DIR / "simulated_medicaid_coverage_agewindow.csv")

# ── Clean coverage data ───────────────────────────────────────────────────────

raw_df[START_COL] = pd.to_datetime(raw_df[START_COL], errors="coerce")
raw_df[END_COL]   = pd.to_datetime(raw_df[END_COL],   errors="coerce")
cov = raw_df.dropna(subset=[ENTITY_COL, START_COL, END_COL]).copy()
cov = cov[(cov[START_COL] >= DATE_FLOOR) & (cov[END_COL] <= DATE_CEILING)]
cov = cov[cov[END_COL] >= cov[START_COL]]
cov = cov.drop_duplicates()

# ── Compute age-based observation windows ────────────────────────────────────

demog_df["dob"] = pd.to_datetime(demog_df[DOB_COL], errors="coerce")
obs_rows = []
for _, row in demog_df.iterrows():
    dob = row["dob"]
    if pd.isna(dob):
        continue
    try:
        obs_start = dob.replace(year=dob.year + AGE_START)
    except ValueError:
        obs_start = dob.replace(year=dob.year + AGE_START, day=28)
    try:
        obs_end = dob.replace(year=dob.year + AGE_END)
    except ValueError:
        obs_end = dob.replace(year=dob.year + AGE_END, day=28)

    obs_start = max(obs_start, DATA_START)
    obs_end   = min(obs_end,   DATA_END)
    obs_days  = max(0, (obs_end - obs_start).days)

    obs_rows.append({
        ENTITY_COL: row[ENTITY_COL],
        "obs_start": obs_start,
        "obs_end":   obs_end,
        "obs_days":  obs_days,
    })

obs_df = pd.DataFrame(obs_rows)

# ── Sample 50 members ─────────────────────────────────────────────────────────

rng        = np.random.default_rng(RANDOM_SEED)
sample_ids = rng.choice(obs_df[ENTITY_COL].unique(), size=N_SAMPLE, replace=False)
obs_sample = obs_df[obs_df[ENTITY_COL].isin(sample_ids)].reset_index(drop=True)

# ── Clip coverage to obs window ───────────────────────────────────────────────

cov_sample = cov[cov[ENTITY_COL].isin(sample_ids)].copy()
cov_sample = cov_sample.merge(
    obs_sample[[ENTITY_COL, "obs_start", "obs_end"]], on=ENTITY_COL, how="left"
)
cov_sample = cov_sample[
    (cov_sample[START_COL] <= cov_sample["obs_end"]) &
    (cov_sample[END_COL]   >= cov_sample["obs_start"])
].copy()
cov_sample["clip_start"] = cov_sample[[START_COL, "obs_start"]].max(axis=1)
cov_sample["clip_end"]   = cov_sample[[END_COL,   "obs_end"]].min(axis=1)

# ── Build plot ────────────────────────────────────────────────────────────────

plt.style.use(STYLE)

n_rows     = len(obs_sample)
fig_height = max(FIG_HEIGHT, n_rows * ROW_HEIGHT + 2)
fig, ax    = plt.subplots(figsize=(FIG_WIDTH, fig_height), dpi=100)

# We need a shared x-axis in normalized time (0=obs_start, 1=obs_end)
# since each member has a different absolute date range.
# Convert all dates to position within [0, 1] relative to obs window.

def to_norm(date, obs_start, obs_end):
    total = (obs_end - obs_start).days
    if total == 0:
        return 0.0
    return (date - obs_start).days / total

for row_idx, (_, obs_row) in enumerate(obs_sample.iterrows()):
    entity    = obs_row[ENTITY_COL]
    obs_start = obs_row["obs_start"]
    obs_end   = obs_row["obs_end"]
    obs_days  = obs_row["obs_days"]
    y         = row_idx
    bar_h     = BAR_HEIGHT * ROW_HEIGHT

    if obs_days == 0:
        # Zero-length window — draw empty bar
        ax.barh(y, 1.0, left=0.0, height=bar_h,
                color=COLOR_NO_EPISODES, edgecolor=BOUNDARY_COLOR,
                linewidth=0.5, align="center")
        continue

    # Draw full obs period as background
    ax.barh(y, 1.0, left=0.0, height=bar_h,
            color=COLOR_BEFORE, edgecolor=BOUNDARY_COLOR,
            linewidth=0.5, align="center")

    # Get coverage periods for this member
    member_cov = cov_sample[cov_sample[ENTITY_COL] == entity].sort_values("clip_start")

    if member_cov.empty:
        # No coverage — already drawn as before color
        continue

    # Draw active coverage segments
    prev_end_norm = None
    for _, cov_row in member_cov.iterrows():
        seg_start_norm = to_norm(cov_row["clip_start"], obs_start, obs_end)
        seg_end_norm   = to_norm(cov_row["clip_end"],   obs_start, obs_end)
        seg_width      = seg_end_norm - seg_start_norm

        if seg_width <= 0:
            continue

        # Draw gap before this segment if there was a previous segment
        if prev_end_norm is not None and seg_start_norm > prev_end_norm:
            gap_width = seg_start_norm - prev_end_norm
            ax.barh(y, gap_width, left=prev_end_norm, height=bar_h,
                    color=COLOR_GAP, align="center")

        # Draw active segment
        ax.barh(y, seg_width, left=seg_start_norm, height=bar_h,
                color=COLOR_ACTIVE, alpha=ALPHA_ACTIVE, align="center")

        prev_end_norm = seg_end_norm

    # Draw after segment
    if prev_end_norm is not None and prev_end_norm < 1.0:
        after_width = 1.0 - prev_end_norm
        ax.barh(y, after_width, left=prev_end_norm, height=bar_h,
                color=COLOR_AFTER, align="center")

# ── Axes formatting ───────────────────────────────────────────────────────────
# Note: because we normalized to [0,1], we cannot show real dates on the x-axis
# without significant additional work to map tick positions back to dates.
# For a heterogeneous cohort with different obs windows, showing real dates
# on a shared axis is not meaningful anyway — this is a fundamental limitation
# of the script-based approach.

ax.set_xlim(0, 1)
ax.set_ylim(-0.5, n_rows - 0.5)
ax.set_xlabel("Normalized observation period (0 = age 18, 1 = age 25)",
              fontsize=FONT_SIZE)
ax.set_yticks([])
ax.set_title("Medicaid Coverage Ages 18-25 (n=50 sample)",
             fontsize=TITLE_FONT_SIZE, pad=15)

# ── Legend ────────────────────────────────────────────────────────────────────

legend_elements = [
    mpatches.Patch(color=COLOR_ACTIVE,    alpha=ALPHA_ACTIVE, label="Medicaid Coverage"),
    mpatches.Patch(color=COLOR_GAP,       label="Coverage Gap"),
    mpatches.Patch(color=COLOR_BEFORE,    label="Before/After Window"),
    mpatches.Patch(color=COLOR_NO_EPISODES, label="No Coverage"),
]
ax.legend(handles=legend_elements, loc="upper right",
          fontsize=9, framealpha=0.9)

plt.tight_layout()
out_path = OUTPUT_DIR / "age_window_coverage_timeline_no_eventus.png"
plt.savefig(out_path, dpi=100, bbox_inches="tight")
plt.close()

print(f"Saved: {out_path}")

# ── What you do NOT get ───────────────────────────────────────────────────────
#
# DISCLAIMER: This script is not meant to be optimized — it is meant
# to be honest. For production use, use eventus.
#
# - The x-axis shows normalized time [0,1] not real dates. Mapping
#   normalized positions back to actual calendar dates for a
#   heterogeneous cohort requires significant additional work.
#   eventus handles this automatically with x_axis: auto.
#
# - All visual constants are hardcoded at the top. Changing the gap
#   color, font size, or bar height requires editing this file.
#   eventus reads these from a versioned YAML config.
#
# - No validation. If you pass a wrong color hex or an invalid
#   figsize, matplotlib either silently ignores it or crashes with
#   a cryptic error. eventus raises at construction with a specific
#   actionable message.
#
# - Not reusable. To produce the same plot for a calendar-year
#   cohort, you rewrite. To add events as dots, you rewrite.
#   eventus adds one entry to the config.
