"""
without_eventus_events.py

Implements the calendar year 2022 ED visit volume analysis from
Chapter 6 of the eventus vignette series using standard pandas — no eventus.

Covers:
  - Cleaning ED visit data
  - Consolidating same-date same-hospital records
  - Filtering to 2022 observation period
  - Computing volume statistics with correct denominators

Does NOT implement the age window analysis (Bonus B). See note at
the bottom for why.

Generated by a large language model given identical specifications.

Run from repo root:
    python vignettes/without_eventus/without_eventus_events.py
"""
import pathlib
import numpy as np
import pandas as pd

# ── Global constants ──────────────────────────────────────────────────────────

ENTITY_COL   = "patient_id"
DATE_COL     = "ed_visit_date"
HOSPITAL_COL = "hospital_id"       # also_defined_by
CONDITION_COL = "icd10_condition"  # descriptor — aggregated as unique
BP_COL        = "systolic_bp"      # descriptor — aggregated as median

DATE_FLOOR   = pd.Timestamp("1920-01-01")
DATE_CEILING = pd.Timestamp("2030-01-01")

OBS_START    = pd.Timestamp("2022-01-01")
OBS_END      = pd.Timestamp("2022-12-31")

# ── Load data ─────────────────────────────────────────────────────────────────

DATA_DIR = pathlib.Path(__file__).parent.parent / "data"
df       = pd.read_csv(DATA_DIR / "ch01_06_ed_visits.csv")
n_input  = len(df)

# ── Clean ─────────────────────────────────────────────────────────────────────

rejection_counts = {}
rejected_frames  = []

df[DATE_COL] = pd.to_datetime(df[DATE_COL], errors="coerce")

mask = df[ENTITY_COL].isna()
rejection_counts["null_entity_id"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="null_entity_id"))
df   = df[~mask].copy()

mask = df[DATE_COL].isna()
rejection_counts["null_date"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="null_date"))
df   = df[~mask].copy()

mask = (df[DATE_COL] < DATE_FLOOR) | (df[DATE_COL] > DATE_CEILING)
rejection_counts["implausible_dates"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="implausible_dates"))
df   = df[~mask].copy()

mask = df.duplicated(keep="first")
rejection_counts["duplicate_row"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="duplicate_row"))
df   = df[~mask].copy()

n_before_consolidate = len(df)

# ── Consolidate same-date same-hospital records ───────────────────────────────
# Two records with the same patient + date + hospital are the same visit
# recorded with different clinical values. Aggregate descriptors.
#
# HOSPITAL_COL, CONDITION_COL, and BP_COL are hardcoded below — they appear
# independently from the constants above. Renaming requires editing multiple
# places.

group_cols = [ENTITY_COL, DATE_COL, HOSPITAL_COL]

consolidated = df.groupby(group_cols, sort=False).agg(
    icd10_condition = (CONDITION_COL, lambda x:
        " | ".join(sorted(set(str(v) for v in x.dropna())))
        if x.notna().any() else None),
    systolic_bp     = (BP_COL, lambda x:
        round(float(pd.to_numeric(x, errors="coerce").dropna().median()), 1)
        if pd.to_numeric(x, errors="coerce").dropna().size > 0 else None),
).reset_index()

# ── Filter to 2022 observation period ────────────────────────────────────────

in_2022 = consolidated[
    (consolidated[DATE_COL] >= OBS_START) &
    (consolidated[DATE_COL] <= OBS_END)
].copy()

# ── Load coverage data to get the 2022 member list ───────────────────────────
# Need the denominator — only members with a defined 2022 obs period.
# This requires loading and cleaning the coverage file just to get member IDs.

cov_df       = pd.read_csv(DATA_DIR / "ch04_06_medicaid_coverage.csv")
cov_df       = cov_df.dropna(subset=[ENTITY_COL]).drop_duplicates(subset=[ENTITY_COL])
members_2022 = set(cov_df[ENTITY_COL].unique())
n_total      = len(members_2022)

# ── Compute volume statistics ─────────────────────────────────────────────────

visit_counts = (
    in_2022[in_2022[ENTITY_COL].isin(members_2022)]
    .groupby(ENTITY_COL)
    .size()
    .reindex(list(members_2022), fill_value=0)
)

n_any      = int((visit_counts > 0).sum())
n_multiple = int((visit_counts > 1).sum())
n_none     = n_total - n_any

# ── Print report ──────────────────────────────────────────────────────────────

rejected_df = pd.concat(rejected_frames, ignore_index=True) if rejected_frames else pd.DataFrame()
n_rejected  = n_input - n_before_consolidate

print(f"Cleaning report (no eventus)")
print(f"{'─' * 56}")
print(f"{'Total input rows:':<42} {n_input:>8,}")
for reason, count in rejection_counts.items():
    pct = round(100 * count / n_input, 1)
    print(f"  {reason:<40} {count:>6,}   ({pct}%)")
print(f"{'─' * 56}")
print(f"{'Total rejected:':<42} {n_rejected:>8,}   ({round(100*n_rejected/n_input,1)}%)")
print(f"{'Clean rows (before consolidation):':<42} {n_before_consolidate:>8,}")
print(f"{'Clean rows (after consolidation):':<42} {len(consolidated):>8,}")
print(f"{'ED visits in 2022:':<42} {len(in_2022):>8,}")

print(f"\nVolume summary — Calendar 2022")
print(f"{'─' * 56}")
print(f"{'Total members (denominator):':<42} {n_total:>8,}")
print(f"{'Any ED visit:':<42} {n_any:>8,}   ({round(100*n_any/n_total,1)}%)")
print(f"{'Multiple ED visits:':<42} {n_multiple:>8,}   ({round(100*n_multiple/n_total,1)}%)")
print(f"{'No ED visit:':<42} {n_none:>8,}   ({round(100*n_none/n_total,1)}%)")

print(f"\nDistribution:")
for n, c in visit_counts.value_counts().sort_index().items():
    label = f"{n} visit{'s' if n != 1 else ''}"
    print(f"  {label:<12} : {c:>4,}  ({round(100*c/n_total,1)}%)")

# ── What you do NOT get — and what would break for Bonus B ────────────────────
#
# DISCLAIMER: This script is not meant to be optimized — it is meant
# to be honest. For production use, use eventus.
#
# This script required ~110 lines to implement the calendar year analysis.
#
# Key observations:
#
# - HOSPITAL_COL, CONDITION_COL, and BP_COL appear independently from
#   the global constants in the consolidation groupby — renaming requires
#   finding every reference manually.
#
# - The denominator (members_2022) required loading and processing the
#   coverage file separately — 4 extra lines that are easy to get wrong.
#   eventus validates the denominator at construction.
#
# - No per-row audit trail — rejected_df has no _rejection_reason column
#   built automatically. It was added manually at each step.
#
# - No structured result object — the summary is a printout. It cannot
#   be stored, compared across cohorts, or passed downstream.
#
# ── Why Bonus B (age window) was not implemented ──────────────────────────────
#
# The age window analysis requires:
#   1. Computing each member's 18th and 21st birthday (~15 lines)
#   2. Handling Feb 29 birthdays explicitly (~5 lines)
#   3. Clipping each member's visits to their personal window — a
#      per-entity merge and filter, not a simple date filter (~25 lines)
#   4. Handling members outside the window (obs_days = 0) — explicit
#      logic to avoid corrupting the denominator (~10 lines)
#   5. Recomputing volume statistics against a new per-entity denominator
#      (~20 lines)
#
# Estimated additional ~75 lines for Bonus B — bringing the total to
# ~185 lines for both analyses combined, with manual denominator tracking
# and no reuse of the calendar year pipeline.
#
# With eventus, Bonus B is 8 lines. The only change is the constructor:
#   ObsPeriodPerEntity.construct_from_age_window(...)
# Everything else is identical to the calendar year analysis.
