"""
without_eventus_observation_periods.py

Implements the same analysis as Chapter 4 of the eventus vignette
series using standard pandas — no eventus.

Covers:
  Part 1 — Calendar year 2022 observation period
  Part 2 — Age-based observation period (ages 18-25)

Generated by a large language model given identical specifications.
This script is included to honestly demonstrate the complexity of
the script-based paradigm for this type of analysis.

Run from repo root:
    python vignettes/without_eventus/without_eventus_observation_periods.py
"""
import pathlib
import warnings
import numpy as np
import pandas as pd

# ── Global constants ──────────────────────────────────────────────────────────

ENTITY_COL    = "patient_id"
START_COL     = "coverage_start"
END_COL       = "coverage_end"
DOB_COL       = "date_of_birth"

DATE_FLOOR    = pd.Timestamp("1920-01-01")
DATE_CEILING  = pd.Timestamp("2030-01-01")

OBS_START_2022 = pd.Timestamp("2022-01-01")
OBS_END_2022   = pd.Timestamp("2022-12-31")

DATA_START    = pd.Timestamp("2018-01-01")
DATA_END      = pd.Timestamp("2025-12-31")

AGE_START     = 18
AGE_END       = 25

# ── Load data ─────────────────────────────────────────────────────────────────

DATA_DIR = pathlib.Path(__file__).parent.parent / "data"

raw_cov   = pd.read_csv(DATA_DIR / "ch04_06_medicaid_coverage.csv")
raw_age   = pd.read_csv(DATA_DIR / "ch04_05_medicaid_coverage_agewindow.csv")
demog_df  = pd.read_csv(DATA_DIR / "ch04_07_member_demographics_mixed_dob.csv")

# ── Shared cleaning function ──────────────────────────────────────────────────

def clean_coverage(df: pd.DataFrame) -> pd.DataFrame:
    """
    Clean a coverage DataFrame.
    Drops nulls, bad dates, causality violations, duplicates.
    Returns a rejection count dict alongside the clean DataFrame.
    """
    rejection_counts = {}
    rejected_frames  = []

    df = df.copy()
    df[START_COL] = pd.to_datetime(df[START_COL], errors="coerce")
    df[END_COL]   = pd.to_datetime(df[END_COL],   errors="coerce")

    mask = df[ENTITY_COL].isna()
    rejection_counts["null_entity_id"] = int(mask.sum())
    rejected_frames.append(df[mask].assign(_reason="null_entity_id"))
    df = df[~mask].copy()

    mask = df[START_COL].isna()
    rejection_counts["null_start_date"] = int(mask.sum())
    rejected_frames.append(df[mask].assign(_reason="null_start_date"))
    df = df[~mask].copy()

    mask = df[END_COL].isna()
    rejection_counts["null_end_date"] = int(mask.sum())
    rejected_frames.append(df[mask].assign(_reason="null_end_date"))
    df = df[~mask].copy()

    mask = (df[START_COL] < DATE_FLOOR) | (df[END_COL] > DATE_CEILING)
    rejection_counts["implausible_dates"] = int(mask.sum())
    rejected_frames.append(df[mask].assign(_reason="implausible_dates"))
    df = df[~mask].copy()

    mask = df[END_COL] < df[START_COL]
    rejection_counts["causality"] = int(mask.sum())
    rejected_frames.append(df[mask].assign(_reason="causality"))
    df = df[~mask].copy()

    mask = df.duplicated(keep="first")
    rejection_counts["duplicate_row"] = int(mask.sum())
    rejected_frames.append(df[mask].assign(_reason="duplicate_row"))
    df = df[~mask].copy()

    return df.reset_index(drop=True), rejection_counts


# ── Shared coverage stats function ───────────────────────────────────────────

def compute_coverage_stats(
    cov_df:    pd.DataFrame,
    obs_df:    pd.DataFrame,
) -> pd.DataFrame:
    """
    Compute per-member coverage statistics within their observation window.

    Parameters
    ----------
    cov_df : pd.DataFrame
        Clean coverage periods with ENTITY_COL, START_COL, END_COL.
    obs_df : pd.DataFrame
        One row per member with ENTITY_COL, obs_start, obs_end, obs_days.

    Returns
    -------
    pd.DataFrame
        One row per member with coverage statistics.
    """
    # Merge obs period onto coverage
    merged = cov_df.merge(
        obs_df[["patient_id", "obs_start", "obs_end", "obs_days"]],
        on="patient_id", how="right",
    )

    # Keep only members with positive obs period
    merged = merged[merged["obs_days"] > 0].copy()

    # Drop coverage periods entirely outside obs window
    has_coverage = merged[START_COL].notna()
    in_window    = (
        merged[START_COL] <= merged["obs_end"]
    ) & (
        merged[END_COL]   >= merged["obs_start"]
    )
    merged = merged[~has_coverage | in_window].copy()

    # Clip coverage to obs window
    merged["clip_start"] = merged[[START_COL, "obs_start"]].max(axis=1)
    merged["clip_end"]   = merged[[END_COL,   "obs_end"]].min(axis=1)
    merged["clip_days"]  = (merged["clip_end"] - merged["clip_start"]).dt.days

    stats_rows = []

    for pid, obs_row in obs_df.iterrows():
        entity      = obs_row["patient_id"]
        obs_start   = obs_row["obs_start"]
        obs_end     = obs_row["obs_end"]
        obs_days    = obs_row["obs_days"]

        if obs_days <= 0:
            stats_rows.append({
                "patient_id":                    entity,
                "obs_days":                      0,
                "active_days":                   0,
                "inactive_days":                 0,
                "inactive_before_first":         None,
                "inactive_after_last":           None,
                "inactive_middle":               0,
                "has_coverage":                  False,
                "n_periods":                     0,
            })
            continue

        member_cov = merged[
            (merged["patient_id"] == entity) & merged[START_COL].notna()
        ].sort_values("clip_start")

        if member_cov.empty:
            stats_rows.append({
                "patient_id":                    entity,
                "obs_days":                      obs_days,
                "active_days":                   0,
                "inactive_days":                 obs_days,
                "inactive_before_first":         None,
                "inactive_after_last":           None,
                "inactive_middle":               0,
                "has_coverage":                  False,
                "n_periods":                     0,
            })
            continue

        active_days = int(member_cov["clip_days"].sum())
        first_start = member_cov["clip_start"].iloc[0]
        last_end    = member_cov["clip_end"].iloc[-1]

        inactive_before = (first_start - obs_start).days
        inactive_after  = (obs_end    - last_end).days

        # Middle gaps — sum of gaps between consecutive periods
        inactive_middle = 0
        periods = member_cov[["clip_start", "clip_end"]].values
        for i in range(1, len(periods)):
            gap = (periods[i][0] - periods[i-1][1]).days
            if gap > 0:
                inactive_middle += gap

        inactive_days = obs_days - active_days

        stats_rows.append({
            "patient_id":            entity,
            "obs_days":              obs_days,
            "active_days":           active_days,
            "inactive_days":         inactive_days,
            "inactive_before_first": inactive_before,
            "inactive_after_last":   inactive_after,
            "inactive_middle":       inactive_middle,
            "has_coverage":          True,
            "n_periods":             len(member_cov),
        })

    return pd.DataFrame(stats_rows)


# ── Shared summary printer ────────────────────────────────────────────────────

def print_summary(stats: pd.DataFrame, label: str) -> None:
    """
    Print a three-tier coverage summary.
    Note: denominators must be tracked manually — easy to mix up.
    """
    n_total    = len(stats)
    covered    = stats[stats["has_coverage"]]
    n_covered  = len(covered)
    n_none     = n_total - n_covered

    print(f"\nCoverage summary — {label}")
    print(f"{'─' * 56}")

    # Tier 1 — denominator: all entities
    print(f"Tier 1 (denominator: all {n_total} entities)")
    print(f"  No coverage  : {n_none:,} ({round(100*n_none/n_total,1)}%)")
    print(f"  Any coverage : {n_covered:,} ({round(100*n_covered/n_total,1)}%)")

    if n_covered == 0:
        return

    # Tier 2 — denominator: covered entities only
    full_cov     = covered[covered["inactive_days"] == 0]
    entered_late = covered[covered["inactive_before_first"] > 0]
    exited_early = covered[covered["inactive_after_last"]   > 0]
    has_gaps     = covered[covered["inactive_middle"]       > 0]

    print(f"\nTier 2 (denominator: {n_covered} covered entities)")
    print(f"  Full coverage     : {len(full_cov):,} ({round(100*len(full_cov)/n_covered,1)}%)")
    print(f"  Entered late      : {len(entered_late):,} ({round(100*len(entered_late)/n_covered,1)}%)")
    print(f"  Exited early      : {len(exited_early):,} ({round(100*len(exited_early)/n_covered,1)}%)")
    print(f"  Has middle gaps   : {len(has_gaps):,} ({round(100*len(has_gaps)/n_covered,1)}%)")

    # Tier 3 — denominator: covered entities only
    def pct_stats(series):
        clean = series.dropna()
        if clean.empty:
            return "no data"
        return (f"mean={clean.mean():.1f}  "
                f"p25={clean.quantile(0.25):.1f}  "
                f"p50={clean.quantile(0.50):.1f}  "
                f"p75={clean.quantile(0.75):.1f}")

    print(f"\nTier 3 (denominator: {n_covered} covered entities)")
    print(f"  active_days   : {pct_stats(covered['active_days'])}")
    print(f"  inactive_days : {pct_stats(covered['inactive_days'])}")


# ── Age window helper ─────────────────────────────────────────────────────────

def compute_age_window(
    demog:     pd.DataFrame,
    age_start: int,
    age_end:   int,
    data_start: pd.Timestamp,
    data_end:   pd.Timestamp,
) -> pd.DataFrame:
    """
    Compute per-member observation window from date of birth.
    Handles Feb 29 birthdays by shifting to Feb 28.
    Clips to data range. Members outside window get obs_days = 0.
    """
    demog = demog.copy()
    demog["dob"] = pd.to_datetime(demog[DOB_COL], errors="coerce")

    obs_starts = []
    obs_ends   = []

    for _, row in demog.iterrows():
        dob = row["dob"]
        if pd.isna(dob):
            obs_starts.append(pd.NaT)
            obs_ends.append(pd.NaT)
            continue

        # Compute age_start birthday — handle Feb 29
        try:
            start = dob.replace(year=dob.year + age_start)
        except ValueError:
            # Feb 29 — shift to Feb 28
            warnings.warn(f"Feb 29 birthday shifted to Feb 28 for entity {row[ENTITY_COL]}")
            start = dob.replace(year=dob.year + age_start, day=28)

        # Compute age_end birthday
        try:
            end = dob.replace(year=dob.year + age_end)
        except ValueError:
            end = dob.replace(year=dob.year + age_end, day=28)

        obs_starts.append(start)
        obs_ends.append(end)

    demog["raw_obs_start"] = obs_starts
    demog["raw_obs_end"]   = obs_ends

    # Clip to data range
    demog["obs_start"] = demog["raw_obs_start"].clip(lower=data_start)
    demog["obs_end"]   = demog["raw_obs_end"].clip(upper=data_end)
    demog["obs_days"]  = (
        (demog["obs_end"] - demog["obs_start"])
        .dt.days
        .clip(lower=0)
    )

    return demog[[ENTITY_COL, "obs_start", "obs_end", "obs_days"]]


# ═══════════════════════════════════════════════════════════════════════════════
# Part 1 — Calendar year 2022
# ═══════════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 56)
print("Part 1 — Calendar year 2022")
print("=" * 56)

cov_clean, rej = clean_coverage(raw_cov)
print(f"Input: {len(raw_cov):,}  Clean: {len(cov_clean):,}  Rejected: {sum(rej.values()):,}")

# Build obs period — one row per member, same dates for all
all_members = cov_clean[ENTITY_COL].unique()
obs_2022 = pd.DataFrame({
    "patient_id": all_members,
    "obs_start":  OBS_START_2022,
    "obs_end":    OBS_END_2022,
    "obs_days":   (OBS_END_2022 - OBS_START_2022).days,
})

stats_2022 = compute_coverage_stats(cov_clean, obs_2022)
print_summary(stats_2022, "Calendar 2022")

# ═══════════════════════════════════════════════════════════════════════════════
# Part 2 — Age window 18-25
# ═══════════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 56)
print("Part 2 — Age window 18-25")
print("=" * 56)

age_clean, rej2 = clean_coverage(raw_age)
print(f"Input: {len(raw_age):,}  Clean: {len(age_clean):,}  Rejected: {sum(rej2.values()):,}")

obs_age = compute_age_window(demog_df, AGE_START, AGE_END, DATA_START, DATA_END)
print(f"Members in window  : {(obs_age['obs_days'] > 0).sum()}")
print(f"Members out of window: {(obs_age['obs_days'] == 0).sum()}")

stats_age = compute_coverage_stats(age_clean, obs_age)
print_summary(stats_age, "Age window 18-25")

# ── What you do NOT get ───────────────────────────────────────────────────────
#
# DISCLAIMER: This script is not meant to be optimized — it is meant
# to be honest. A more experienced pandas developer could condense
# some functions. The point is not the line count. It is what the
# lines are doing and what they are missing. For production use,
# use eventus.
#
# This script required ~275 lines to implement feature parity with
# Chapter 4 of the eventus vignette. Key observations:
#
# - No bad input validation beyond basic cleaning. The eventus
#   cleaner validates column names, causality, date floors, and
#   produces a per-row audit trail. This script has none of that.
#
# - No specific errors raised. The pandas UserWarning above is not
#   an exception — execution continues and may produce wrong output
#   silently. eventus raises at construction with a specific,
#   actionable message before any data is touched.
#
# - compute_coverage_stats() iterates over every member in a Python
#   loop — this does not scale to large cohorts.
#
# - Denominator tracking is manual throughout print_summary().
#   One mistake produces wrong statistics silently.
#
# - compute_age_window() required 40 lines including the Feb 29
#   edge case. eventus handles this in one constructor argument.
#
# - No equivalent of EpisodeCoverageSummary — the structured object
#   with validated denominators and named tiers does not exist.
#   The summary is a printout that cannot be stored, compared,
#   or passed downstream.
#
# - No enriched CohortTimeline — computed statistics must be
#   recomputed every time they are needed downstream.
