"""
without_eventus_clean_hospitalizations.py

Cleans hospitalization claims using standard pandas — no eventus.

Implements the same pipeline as Chapter 1 of the eventus vignette:
  - Drop null patient IDs
  - Drop null admit or discharge dates
  - Drop implausible dates (before 1920, after 2030)
  - Enforce causality (admit <= discharge)
  - Drop exact duplicate rows
  - Merge overlapping stays at the SAME hospital (transfer-aware)
  - Aggregate icd10_condition across merged rows (unique values)

Generated by a large language model given identical specifications.
Refactored to use global constants — the fairest comparison against
eventus.

Loads from the same synthetic dataset used in the eventus vignettes:
    vignettes/data/hospitalization_claims.csv

Run from repo root:
    python vignettes/without_eventus/without_eventus_clean_hospitalizations.py
"""
import pathlib
import pandas as pd

# ── Global constants ──────────────────────────────────────────────────────────

ENTITY_COL     = "patient_id"
START_COL      = "admit_date"
END_COL        = "discharge_date"
HOSPITAL_COL   = "hospital_id"       # also_defined_by — merging respects this
CONDITION_COL  = "icd10_condition"   # descriptor — aggregated during merge

DATE_FLOOR     = pd.Timestamp("1920-01-01")
DATE_CEILING   = pd.Timestamp("2030-01-01")
MEANINGFUL_GAP = 1   # days

# ── Load data ─────────────────────────────────────────────────────────────────

DATA_PATH   = pathlib.Path(__file__).parent.parent / "data" / "ch01_hospitalization_claims.csv"
df          = pd.read_csv(DATA_PATH)
n_input     = len(df)
print(f"Input rows: {n_input:,}")

# ── Track rejections ──────────────────────────────────────────────────────────
# Note: this is aggregate only — no per-row record is kept.
# To inspect individual rejected rows you would need to store them
# separately at each step — not implemented here.

rejection_counts = {}
rejected_frames  = []   # attempt at per-row tracking — adds ~15 lines

# ── Parse dates ───────────────────────────────────────────────────────────────

df[START_COL] = pd.to_datetime(df[START_COL], errors="coerce")
df[END_COL]   = pd.to_datetime(df[END_COL],   errors="coerce")

# ── Drop null entity IDs ──────────────────────────────────────────────────────

mask = df[ENTITY_COL].isna()
rejection_counts["null_entity_id"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="null_entity_id"))
df   = df[~mask].copy()

# ── Drop null start dates ─────────────────────────────────────────────────────

mask = df[START_COL].isna()
rejection_counts["null_start_date"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="null_start_date"))
df   = df[~mask].copy()

# ── Drop null end dates ───────────────────────────────────────────────────────

mask = df[END_COL].isna()
rejection_counts["null_end_date"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="null_end_date"))
df   = df[~mask].copy()

# ── Drop implausible dates ────────────────────────────────────────────────────

mask = (df[START_COL] < DATE_FLOOR) | (df[END_COL] > DATE_CEILING)
rejection_counts["implausible_dates"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="implausible_dates"))
df   = df[~mask].copy()

# ── Enforce causality ─────────────────────────────────────────────────────────

mask = df[END_COL] < df[START_COL]
rejection_counts["end_before_start"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="end_before_start"))
df   = df[~mask].copy()

# ── Drop duplicate rows ───────────────────────────────────────────────────────

mask = df.duplicated(keep="first")
rejection_counts["duplicate_row"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="duplicate_row"))
df   = df[~mask].copy()

n_before_merge = len(df)

# ── Merge overlapping stays — transfer-aware ──────────────────────────────────
# Group by patient AND hospital — two overlapping stays at different
# hospitals are a transfer and must not be merged.
# This requires grouping by [ENTITY_COL, HOSPITAL_COL], not just ENTITY_COL.
# icd10_condition is aggregated as unique pipe-delimited values.
#
# Note: HOSPITAL_COL and CONDITION_COL must be hardcoded here.
# If your data warehouse renames these columns, this block breaks in
# multiple places independently from the column constants above.

gap_threshold = pd.Timedelta(days=MEANINGFUL_GAP)
merged_rows   = []

for (entity, hospital), group in df.groupby([ENTITY_COL, HOSPITAL_COL]):
    group = group.sort_values(START_COL).reset_index(drop=True)

    current_start     = group.at[0, START_COL]
    current_end       = group.at[0, END_COL]
    current_conditions = [str(group.at[0, CONDITION_COL])]

    for _, row in group.iloc[1:].iterrows():
        if row[START_COL] - current_end <= gap_threshold:
            current_end = max(current_end, row[END_COL])
            current_conditions.append(str(row[CONDITION_COL]))
        else:
            unique_conditions = " | ".join(
                sorted(set(c for c in current_conditions
                           if c not in ("nan", "None", "")))
            )
            merged_rows.append({
                ENTITY_COL:    entity,
                HOSPITAL_COL:  hospital,
                START_COL:     current_start,
                END_COL:       current_end,
                CONDITION_COL: unique_conditions,
            })
            current_start      = row[START_COL]
            current_end        = row[END_COL]
            current_conditions = [str(row[CONDITION_COL])]

    unique_conditions = " | ".join(
        sorted(set(c for c in current_conditions
                   if c not in ("nan", "None", "")))
    )
    merged_rows.append({
        ENTITY_COL:    entity,
        HOSPITAL_COL:  hospital,
        START_COL:     current_start,
        END_COL:       current_end,
        CONDITION_COL: unique_conditions,
    })

clean_df = pd.DataFrame(merged_rows).reset_index(drop=True)

# ── Combine rejected rows ─────────────────────────────────────────────────────

rejected_df = pd.concat(rejected_frames, ignore_index=True) \
    if rejected_frames else pd.DataFrame()

# ── Print report ──────────────────────────────────────────────────────────────

n_rejected = n_input - n_before_merge
n_clean    = len(clean_df)

print(f"\nCleaning report (no eventus)")
print(f"{'─' * 56}")
print(f"{'Total input rows:':<42} {n_input:>8,}")
print(f"{'─' * 56}")
for reason, count in rejection_counts.items():
    pct = round(100 * count / n_input, 1)
    print(f"  {reason:<40} {count:>6,}   ({pct}%)")
print(f"{'─' * 56}")
print(
    f"{'Total rejected:':<42} {n_rejected:>8,}"
    f"   ({round(100 * n_rejected / n_input, 1)}%)"
)
print(f"{'Clean rows (before merge):':<42} {n_before_merge:>8,}")
print(f"{'Clean rows (after merge):':<42} {n_clean:>8,}")
print(f"\nUnique entities: {clean_df[ENTITY_COL].nunique():,}")

# ── What you do NOT get ───────────────────────────────────────────────────────
#
# - Per-row rejection record is aggregate only — rejected_df exists
#   but required ~15 extra lines to build and has no _rejection_reason
#   column, just a _reason column we added manually at each step.
#
# - HOSPITAL_COL and CONDITION_COL are hardcoded in the merge loop above
#   independently of the global constants — the loop breaks if you rename
#   them even after updating the constants at the top.
#
# - MEANINGFUL_GAP, DATE_FLOOR, DATE_CEILING are global constants —
#   not versioned, not in a config file. A collaborator reading the
#   output has no way to reconstruct these choices without reading
#   the source code.
#
# - Adding a third grouping column (e.g. provider_id) requires rewriting
#   the merge loop — it is not a config change.
#
# - Adding a second descriptor column (e.g. bmi_at_admission) with a
#   different aggregation rule (median instead of unique) requires
#   adding more hardcoded logic inside the merge loop.
