"""
without_eventus_clean_ed_visits.py

Cleans ED visit event data using standard pandas — no eventus.

Implements the same pipeline as the Bonus A section of Chapter 1:
  - Drop null patient IDs
  - Drop null visit dates
  - Drop implausible dates (before 1920, after 2030)
  - Drop duplicate rows (whole-row deduplication)
  - Hospital-aware deduplication: two visits on the same date at
    different hospitals are NOT duplicates — they are separate episodes

Generated by a large language model given identical specifications.
Refactored to use global constants — the fairest comparison against
eventus.

Loads from the same synthetic dataset used in the eventus vignettes:
    vignettes/data/ed_visits.csv

Run from repo root:
    python vignettes/without_eventus/without_eventus_clean_ed_visits.py
"""
import pathlib
import pandas as pd

# ── Global constants ──────────────────────────────────────────────────────────

ENTITY_COL   = "patient_id"
DATE_COL     = "ed_visit_date"
HOSPITAL_COL = "hospital_id"    # also_defined_by — dedup respects this

DATE_FLOOR   = pd.Timestamp("1920-01-01")
DATE_CEILING = pd.Timestamp("2030-01-01")

# ── Load data ─────────────────────────────────────────────────────────────────

DATA_PATH = pathlib.Path(__file__).parent.parent / "data" / "ed_visits.csv"
df        = pd.read_csv(DATA_PATH)
n_input   = len(df)
print(f"Input rows: {n_input:,}")

# ── Track rejections ──────────────────────────────────────────────────────────

rejection_counts = {}
rejected_frames  = []

# ── Parse dates ───────────────────────────────────────────────────────────────

df[DATE_COL] = pd.to_datetime(df[DATE_COL], errors="coerce")

# ── Drop null entity IDs ──────────────────────────────────────────────────────

mask = df[ENTITY_COL].isna()
rejection_counts["null_entity_id"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="null_entity_id"))
df   = df[~mask].copy()

# ── Drop null dates ───────────────────────────────────────────────────────────

mask = df[DATE_COL].isna()
rejection_counts["null_date"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="null_date"))
df   = df[~mask].copy()

# ── Drop implausible dates ────────────────────────────────────────────────────

mask = (df[DATE_COL] < DATE_FLOOR) | (df[DATE_COL] > DATE_CEILING)
rejection_counts["implausible_dates"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="implausible_dates"))
df   = df[~mask].copy()

# ── Drop duplicate rows (whole-row) ───────────────────────────────────────────
# Two rows are duplicates only if ALL columns match.
# This preserves two visits on the same date at different hospitals —
# those are different episodes, not duplicates.

mask = df.duplicated(keep="first")
rejection_counts["duplicate_row"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="duplicate_row"))
df   = df[~mask].copy()

clean_df   = df.reset_index(drop=True)
n_rejected = n_input - len(clean_df)

# ── Combine rejected rows ─────────────────────────────────────────────────────

rejected_df = pd.concat(rejected_frames, ignore_index=True) \
    if rejected_frames else pd.DataFrame()

# ── Print report ──────────────────────────────────────────────────────────────

print(f"\nCleaning report (no eventus)")
print(f"{'─' * 56}")
print(f"{'Total input rows:':<42} {n_input:>8,}")
print(f"{'─' * 56}")
for reason, count in rejection_counts.items():
    pct = round(100 * count / n_input, 1)
    print(f"  {reason:<40} {count:>6,}   ({pct}%)")
print(f"{'─' * 56}")
print(
    f"{'Total rejected:':<42} {n_rejected:>8,}"
    f"   ({round(100 * n_rejected / n_input, 1)}%)"
)
print(f"{'Clean rows:':<42} {len(clean_df):>8,}")
print(f"\nUnique entities: {clean_df[ENTITY_COL].nunique():,}")

# ── What you do NOT get ───────────────────────────────────────────────────────
#
# - No config file — DATE_FLOOR, DATE_CEILING, HOSPITAL_COL are global
#   constants in this script. Not versioned. Not shareable.
#
# - HOSPITAL_COL is declared as a constant but is not actually used
#   anywhere in the deduplication logic — because whole-row dedup
#   already handles it correctly here. However, if you wanted to
#   explicitly deduplicate on entity + date + hospital while keeping
#   other columns free to differ, you would need to add custom logic.
#
# - No EventSemantics equivalent — if your data warehouse renames
#   a column, you must find every reference manually.
#
# - No consolidate equivalent — if you wanted to aggregate descriptor
#   columns across same-date same-hospital records, you would need to
#   write a custom groupby aggregation block.
