"""
without_eventus_clean_nursing_facility.py

Cleans nursing facility assessment data using standard pandas — no eventus.

Implements the same pipeline as Chapter 2 of the eventus vignette:
  - Drop null resident IDs
  - Drop null admit or discharge dates
  - Drop implausible dates (before 1920, after 2030)
  - Enforce causality (admit <= discharge)
  - Drop duplicate rows (whole-row)
  - Merge assessments into one row per resident per facility stay
  - Aggregate systolic_bp by mean
  - Aggregate bmi by median
  - Aggregate mobility_status by sequence (pipe-delimited in order)

Generated by a large language model given identical specifications.
Refactored to use global constants — the fairest comparison against
eventus.

Loads from the same synthetic dataset used in the eventus vignettes:
    vignettes/data/nursing_facility_assessments.csv

Run from repo root:
    python vignettes/without_eventus/without_eventus_clean_nursing_facility.py
"""
import pathlib
import numpy as np
import pandas as pd

# ── Global constants ──────────────────────────────────────────────────────────

ENTITY_COL      = "resident_id"
START_COL       = "admit_date"
END_COL         = "discharge_date"
FACILITY_COL    = "facility_id"      # also_defined_by

# Descriptor columns and their aggregation rules — hardcoded
SYSTOLIC_COL    = "systolic_bp"      # aggregate by: mean
BMI_COL         = "bmi"              # aggregate by: median
MOBILITY_COL    = "mobility_status"  # aggregate by: sequence

DATE_FLOOR      = pd.Timestamp("1920-01-01")
DATE_CEILING    = pd.Timestamp("2030-01-01")

# ── Load data ─────────────────────────────────────────────────────────────────

DATA_PATH = pathlib.Path(__file__).parent.parent / "data" / "nursing_facility_assessments.csv"
df        = pd.read_csv(DATA_PATH)
n_input   = len(df)
print(f"Input rows: {n_input:,}")

# ── Track rejections ──────────────────────────────────────────────────────────

rejection_counts = {}
rejected_frames  = []

# ── Parse dates ───────────────────────────────────────────────────────────────

df[START_COL] = pd.to_datetime(df[START_COL], errors="coerce")
df[END_COL]   = pd.to_datetime(df[END_COL],   errors="coerce")

# ── Drop null entity IDs ──────────────────────────────────────────────────────

mask = df[ENTITY_COL].isna()
rejection_counts["null_entity_id"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="null_entity_id"))
df   = df[~mask].copy()

# ── Drop null start dates ─────────────────────────────────────────────────────

mask = df[START_COL].isna()
rejection_counts["null_start_date"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="null_start_date"))
df   = df[~mask].copy()

# ── Drop null end dates ───────────────────────────────────────────────────────

mask = df[END_COL].isna()
rejection_counts["null_end_date"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="null_end_date"))
df   = df[~mask].copy()

# ── Drop implausible dates ────────────────────────────────────────────────────

mask = (df[START_COL] < DATE_FLOOR) | (df[END_COL] > DATE_CEILING)
rejection_counts["implausible_dates"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="implausible_dates"))
df   = df[~mask].copy()

# ── Enforce causality ─────────────────────────────────────────────────────────

mask = df[END_COL] < df[START_COL]
rejection_counts["end_before_start"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="end_before_start"))
df   = df[~mask].copy()

# ── Drop duplicate rows ───────────────────────────────────────────────────────

mask = df.duplicated(keep="first")
rejection_counts["duplicate_row"] = int(mask.sum())
rejected_frames.append(df[mask].assign(_reason="duplicate_row"))
df   = df[~mask].copy()

n_before_merge = len(df)

# ── Merge and aggregate ───────────────────────────────────────────────────────
# Group by resident + facility + stay (admit + discharge).
# Each group is one stay. Aggregate each descriptor column separately.
#
# Note: SYSTOLIC_COL uses mean, BMI_COL uses median, MOBILITY_COL uses
# sequence. These rules are hardcoded below. If your statistician asks
# you to change mean to median for systolic_bp, you need to find line 113
# and change it. If you want to add a fourth descriptor column with a
# different rule, you need to add another aggregation block.
# There is no config file recording these choices.

group_cols = [ENTITY_COL, FACILITY_COL, START_COL, END_COL]

clean_df = df.groupby(group_cols, sort=False).agg(
    systolic_bp    = (SYSTOLIC_COL, lambda x:
        round(float(pd.to_numeric(x, errors="coerce").dropna().mean()), 1)
        if pd.to_numeric(x, errors="coerce").dropna().size > 0 else None),
    bmi            = (BMI_COL, lambda x:
        round(float(pd.to_numeric(x, errors="coerce").dropna().median()), 1)
        if pd.to_numeric(x, errors="coerce").dropna().size > 0 else None),
    mobility_status= (MOBILITY_COL, lambda x:
        " | ".join(str(v) for v in x.dropna().tolist())),
).reset_index()

# Ensure consistent rounding
clean_df[SYSTOLIC_COL] = clean_df[SYSTOLIC_COL].round(1)
clean_df[BMI_COL]      = clean_df[BMI_COL].round(1)

n_rejected = n_input - n_before_merge
n_clean    = len(clean_df)

# ── Combine rejected rows ─────────────────────────────────────────────────────

rejected_df = pd.concat(rejected_frames, ignore_index=True) \
    if rejected_frames else pd.DataFrame()

# ── Print report ──────────────────────────────────────────────────────────────

print(f"\nCleaning report (no eventus)")
print(f"{'─' * 56}")
print(f"{'Total input rows:':<42} {n_input:>8,}")
print(f"{'─' * 56}")
for reason, count in rejection_counts.items():
    pct = round(100 * count / n_input, 1)
    print(f"  {reason:<40} {count:>6,}   ({pct}%)")
print(f"{'─' * 56}")
print(
    f"{'Total rejected:':<42} {n_rejected:>8,}"
    f"   ({round(100 * n_rejected / n_input, 1)}%)"
)
print(f"{'Clean rows (before merge):':<42} {n_before_merge:>8,}")
print(f"{'Clean rows (after merge):':<42} {n_clean:>8,}")
print(f"\nUnique residents: {clean_df[ENTITY_COL].nunique():,}")
print(f"\nSample output:")
print(clean_df[[ENTITY_COL, FACILITY_COL, START_COL, END_COL,
                SYSTOLIC_COL, BMI_COL, MOBILITY_COL]].head(3).to_string())

# ── What you do NOT get ───────────────────────────────────────────────────────
#
# - Aggregation rules are hardcoded on lines ~113-122. There is no
#   config file. A collaborator reading the output cannot reconstruct
#   these choices without reading the source code.
#
# - Changing mean to median for systolic_bp requires finding the right
#   line in the script. With eventus: change one word in the YAML.
#
# - Adding a fourth descriptor column requires a new aggregation block.
#   With eventus: add two lines to the semantics YAML and one line to
#   the cleaner YAML.
#
# - Column type (numeric vs category) is implicit — nothing stops you
#   from accidentally applying mean to mobility_status.
#   With eventus: the type is declared in semantics and validated
#   against the aggregation rule at construction.
